---

name: Linters

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222

      - name: Use Node.js 18.x
        uses: actions/setup-node@5b32c9063c6eb277dacbf3e916a8bc5d2617c5b7
        with:
          node-version: 18
          cache: yarn

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Prettier
        run: yarn run format-check

      - name: ESLint
        run: yarn run lint

...
